#pragma once

#include "AFC\Australia\aus_setup.h"
#include "AFC\Iran\irn_setup.h"
#include "AFC\Japan\jpn_setup.h"
#include "AFC\Saudi Arabia\ksa_setup.h"
#include "AFC\South Korea\kor_setup.h"
#include "CAF\Egypt\egy_setup.h"
#include "CAF\Morocco\mar_setup.h"
#include "CONCACAF\USA\usa_setup.h"
#include "CONMEBOL\Argentina\arg_setup.h"
#include "CONMEBOL\Brazil\bra_setup.h"
#include "CONMEBOL\Chile\chi_setup.h"
#include "UEFA\Austria\aut_setup.h"
#include "UEFA\Belgium\bel_setup.h"
#include "UEFA\Croatia\cro_setup.h"
#include "UEFA\Czech Republic\cze_setup.h"
#include "UEFA\Denmark\den_setup.h"
#include "UEFA\England\eng_setup.h"
#include "UEFA\Finland\fin_setup.h"
#include "UEFA\France\fra_setup.h"
#include "UEFA\Germany\ger_setup.h"
#include "UEFA\Greece\gre_setup.h"
#include "UEFA\Holland\hol_setup.h"
#include "UEFA\Ireland\irl_setup.h"
#include "UEFA\Italy\ita_setup.h"
#include "UEFA\Northern Ireland\nir_setup.h"
#include "UEFA\Norway\nor_setup.h"
#include "UEFA\Poland\pol_setup.h"
#include "UEFA\Portugal\por_setup.h"
#include "UEFA\Russia\rus_setup.h"
#include "UEFA\Scotland\sco_setup.h"
#include "UEFA\Serbia\srb_setup.h"
#include "UEFA\Spain\spa_setup.h"
#include "UEFA\Sweden\swe_setup.h"
#include "UEFA\Switzerland\sui_setup.h"
#include "UEFA\Turkey\tur_setup.h"
#include "UEFA\Wales\wal_setup.h"

#include "FIFA\world_cup_comps_setup.h"
#include "FIFA\fifa_national_setup.h"
#include "FIFA\fifa_club_setup.h"
#include "AFC\afc_club_setup.h"
#include "CAF\caf_club_setup.h"
#include "CONCACAF\concacaf_club_setup.h"
#include "CONMEBOL\conmebol_club_setup.h"
#include "OFC\ofc_club_setup.h"
#include "UEFA\uefa_club_setup.h"

void setup_leagues_setup();